export let product = [
  {
      id: 1,
      image_url: "https://m.media-amazon.com/images/I/51-ZMPMS8BL._SX569_.jpg",
      price: "$35.99",
      description: "Men's Puffer Vest - Lightweight and warm, ideal for layering.",
      offer: "Save $10 on your next order",
      type: "men",
  },
  {
      id: 2,
      image_url: "https://m.media-amazon.com/images/I/614Wz-Mr6KL._AC_UL320_.jpg",  // Updated image
      price: "$14.49",
      description: "Kids' Polka Dot Dress - Cute and playful, made from lightweight fabric.",
      offer: "Free shipping ",
      type: "kids",
  },
  {
      id: 3,
      image_url: "https://m.media-amazon.com/images/I/81iCPGSMhCL._AC_UL320_.jpg",
      price: "$22.49",
      description: "Boho Chic Top - Flowy and comfortable with intricate detailing.",
      offer: "Buy 1, get 1 50% off",
      type: "kids",
  },
  {
      id: 4,
      image_url: "https://m.media-amazon.com/images/I/71pTz502KlL._AC_UL320_.jpg",
      price: "$19.99",
      description: "Casual Pink T-shirt - Comfortable and breathable, perfect for everyday wear.",
      offer: "Buy 2, get 1 free",
      type: "women",
  },
  {
      id: 5,
      image_url: "https://m.media-amazon.com/images/I/71dFWXvnHaL._AC_UL320_.jpg",
      price: "$24.99",
      description: "Casual Denim Shirt - Versatile and comfortable, great for everyday wear.",
      offer: "Buy 2, get 1 free",
      type: "men",
  },
  {
      id: 6,
      image_url: "https://m.media-amazon.com/images/I/61Zjr852N3L._AC_UL320_.jpg",
      price: "$14.99",
      description: "Men's Beanie - Warm and cozy, perfect for winter days.",
      offer: "Buy 1, get 1 50% off",
      type: "men",
  },
  {
      id: 7,
      image_url: "https://m.media-amazon.com/images/I/61TJ+FEjuNL._AC_UL320_.jpg",
      price: "$17.99",
      description: "Graphic Crop Top - Trendy and stylish with a bold print.",
      offer: "10% off with code GRAPHIC10",
      type: "women",
  },
  {
      id: 8,
      image_url: "https://m.media-amazon.com/images/I/81SJV8c67WL._AC_UL320_.jpg",
      price: "$29.99",
      description: "Men's Track Jacket - Lightweight and breathable, perfect for workouts.",
      offer: "Save 15% with code TRACK15",
      type: "men",
  },
  {
      id: 9,
      image_url: "https://m.media-amazon.com/images/I/71hZBx4p0mL._AC_UL320_.jpg",  // Updated image
      price: "$15.99",
      description: "Kids' Striped T-Shirt - Soft and breathable, perfect for everyday wear.",
      offer: "Buy 2, get 1 free",
      type: "kids",
  },
  {
      id: 10,
      image_url: "https://m.media-amazon.com/images/I/71EKnp2NkLL._AC_UL320_.jpg",
      price: "$22.99",
      description: "Stylish Off-Shoulder Top - Elegant design with ruffle details.",
      offer: "20% off on orders above $50",
      type: "women",
  },
  {
      id: 11,
      image_url: "https://m.media-amazon.com/images/I/51G0KvN6TsL._AC_UL320_.jpg",  // Updated image
      price: "$16.99",
      description: "Kids' Plaid Shirt - Classic design, great for casual or formal occasions.",
      offer: "10% off on your first order",
      type: "kids",
  },
  {
      id: 12,
      image_url: "https://m.media-amazon.com/images/I/61XELZxf9yL._AC_UL320_.jpg",
      price: "$34.99",
      description: "Men's Classic Leather Jacket - Durable and stylish, perfect for cool weather.",
      offer: "15% off on first purchase",
      type: "men",
  },
  {
      id: 13,
      image_url: "https://m.media-amazon.com/images/I/81KpE2l+ehL._AC_UL320_.jpg",
      price: "$24.99",
      description: "Girls' Floral Print Top - Soft cotton fabric with a vibrant floral design.",
      offer: "10% off on your first purchase",
      type: "women",
  },
  {
      id: 14,
      image_url: "https://m.media-amazon.com/images/I/512Fau61yGL._AC_UL320_.jpg",  // Updated image
      price: "$11.99",
      description: "Kids' Shorts - Comfortable and breathable, ideal for summer playtime.",
      offer: "Buy 2, get free shipping",
      type: "kids",
  },
  {
      id: 15,
      image_url: "https://m.media-amazon.com/images/I/71LMGs6dccL._AC_UL320_.jpg",
      price: "$19.99",
      description: "Casual Ruffle Sleeve Top - Perfect for a relaxed, yet stylish look.",
      offer: "15% off on your first order",
      type: "women",
  },
  {
      id: 16,
      image_url: "https://m.media-amazon.com/images/I/71pAuNaGiQL._AC_UL320_.jpg",
      price: "$25.99",
      description: "Peplum Top - Flattering fit with a flared hem, made from soft fabric.",
      offer: "20% off with code PEPLUM20",
      type: "women",
  },
  {
      id: 17,
      image_url: "https://m.media-amazon.com/images/I/71mmZUZ6JbL._AC_UL320_.jpg",
      price: "$22.99",
      description: "Men's Plaid Shirt - Classic plaid design, perfect for casual outings.",
      offer: "Buy 2, get free shipping",
      type: "men",
  },
  {
      id: 18,
      image_url: "https://m.media-amazon.com/images/I/81ThKfAzc7L._AC_UL320_.jpg",
      price: "$18.99",
      description: "Ribbed Tank Top - Sleek and simple, perfect for layering.",
      offer: "Buy 2, get a third free",
      type: "women",
  },
  {
      id: 19,
      image_url: "https://m.media-amazon.com/images/I/61tRg6LVgeL._AC_UL320_.jpg",
      price: "$42.99",
      description: "Men's Wool Coat - Elegant and warm, perfect for formal occasions.",
      offer: "Free scarf with purchase",
      type: "men",
  },
  {
      id: 20,
      image_url: "https://m.media-amazon.com/images/I/51r8ijy9-uL._AC_UL320_.jpg",  // Updated image
      price: "$19.99",
      description: "Kids' Hoodie - Cozy and warm, perfect for layering in winter.",
      offer: "20% off with code KIDSHOODIE20",
      type: "kids",
  },
  {
      id: 21,
      image_url: "https://m.media-amazon.com/images/I/71rnu8--XcL._AC_UL320_.jpg",
      price: "$27.99",
      description: "Denim Crop Top - Trendy and comfortable, pairs well with jeans or skirts.",
      offer: "Buy 3, save 20%",
      type: "women",
  },
  {
      id: 22,
      image_url: "https://m.media-amazon.com/images/I/81KuuD2e12L._AC_UL320_.jpg",  // Updated image
      price: "$13.49",
      description: "perfect for active days.",
      offer: "Save $5 on your next purchase",
      type: "women",
  },
  {
      id: 23,
      image_url: "https://m.media-amazon.com/images/I/61FVEqUK9qL._AC_UL320_.jpg",
      price: "$24.99",
      description: "Knotted Front Top - Stylish and comfortable with a front knot design.",
      offer: "10% off with code KNOT10",
      type: "women",
  },
  {
      id: 24,
      image_url: "https://m.media-amazon.com/images/I/51a0QHAi7jL._AC_UL320_.jpg",  // Updated image
      price: "$28.99",
      description: "Kids' Overalls - Trendy and durable, perfect for everyday adventures.",
      offer: "Buy 2, get 1 free",
      type: "kids",
  },
  {
      id: 25,
      image_url: "https://m.media-amazon.com/images/I/61kqhTCKtgL._AC_UL320_.jpg",
      price: "$29.99",
      description: "Men's Joggers - Comfortable and stylish, great for workouts or lounging.",
      offer: "20% off with code JOGGER20",
      type: "men",
  },
  {
      id: 26,
      image_url: "https://m.media-amazon.com/images/I/51m-Td-2oJL._AC_UL320_.jpg",  // Updated image
      price: "$17.99",
      description: "Kids' Long Sleeve T-Shirt - Soft and comfortable, perfect for layering.",
      offer: "Buy 2, get 1 free",
      type: "kids",
  },
  {
      id: 27,
      image_url: "https://m.media-amazon.com/images/I/81iCPGSMhCL._AC_UL320_.jpg",
      price: "$21.99",
      description: "Floral Wrap Dress - Elegant and versatile, suitable for various occasions.",
      offer: "Save 15% with code WRAP15",
      type: "kids",
  },
  {
      id: 28,
      image_url: "https://m.media-amazon.com/images/I/512Fau61yGL._AC_UL320_.jpg",
      price: "$14.99",
      description: "Kids' Graphic T-Shirt - Fun and colorful design, made from soft fabric.",
      offer: "Buy 2, get 1 free",
      type: "kids",
  },
  {
      id: 29,
      image_url: "https://m.media-amazon.com/images/I/71x4rLhMkML._AC_UL320_.jpg",
      price: "$24.99",
      description: "Men's Hooded Jacket - Lightweight and versatile, perfect for everyday wear.",
      offer: "Buy 2, get 1 free",
      type: "men",
  },
  {
      id: 30,
      image_url: "https://m.media-amazon.com/images/I/715-Z-aOIhL._AC_UL320_.jpg",
      price: "$18.99",
      description: "V-Neck Blouse - Elegant and chic, perfect for a day at the office.",
      offer: "10% off with code VNECK10",
      type: "women",
  },
  {
      id: 31,
      image_url: "https://m.media-amazon.com/images/I/61vu29fIVSL._AC_UL320_.jpg",
      price: "$27.49",
      description: "Wide-Leg Pants - Comfortable and stylish, perfect for casual wear.",
      offer: "20% off with code WIDELEG20",
      type: "women",
  },
  {
      id: 32,
      image_url: "https://m.media-amazon.com/images/I/71S9kXoGQLL._SX569_.jpg",
      price: "$29.99",
      description: "Men's Denim Jacket - Classic design, durable and perfect for layering.",
      offer: "Save $10 with code DENIM10",
      type: "men",
  },
  {
      id: 33,
      image_url: "https://m.media-amazon.com/images/I/51sjcWuCr+L._AC_UL320_.jpg",
      price: "$22.99",
      description: "Girls' Cotton Dress - Soft and breathable fabric, perfect for everyday wear.",
      offer: "Free shipping",
      type: "kids",
  },
  {
      id: 34,
      image_url: "https://m.media-amazon.com/images/I/517+8nArL8L._AC_UL320_.jpg",  // Updated image
      price: "$14.99",
      description: "Kids' Polka Dot Dress - Cute and playful, made from lightweight fabric.",
      offer: "Free shipping ",
      type: "kids",
  },
  {
    id: 2,
    image_url: "https://m.media-amazon.com/images/I/614Wz-Mr6KL._AC_UL320_.jpg",  // Updated image
    price: "$14.49",
    description: "Kids' Polka Dot Dress - Cute and playful, made from lightweight fabric.",
    offer: "Free shipping ",
    type: "kids",
},
{
    id: 3,
    image_url: "https://m.media-amazon.com/images/I/81iCPGSMhCL._AC_UL320_.jpg",
    price: "$22.49",
    description: "Boho Chic Top - Flowy and comfortable with intricate detailing.",
    offer: "Buy 1, get 1 50% off",
    type: "kids",
}
];
 
export default product;
